"""initial tables

Revision ID: 403a1fe5468c
Revises: 
Create Date: 2026-03-13 20:32:03.360693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  


# revision identifiers, used by Alembic.
revision: str = '403a1fe5468c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'organization', ['org_name'])
    op.add_column('user', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('email_verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_user_org_id'), 'user', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_org_id'), table_name='user')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'refresh_token_hash')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'locked_until')
    op.drop_column('user', 'failed_login_attempts')
    op.drop_column('user', 'email_verification_token')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'full_name')
    op.drop_constraint(None, 'organization', type_='unique')
    op.drop_column('organization', 'is_active')
    # ### end Alembic commands ###
