"""add campaigns leads campaign_settings tables

Revision ID: 52be30293418
Revises: 68fb7f7d8f69
Create Date: 2026-03-15 00:24:49.502953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  


# revision identifiers, used by Alembic.
revision: str = '52be30293418'
down_revision: Union[str, Sequence[str], None] = '68fb7f7d8f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_campaign_org_id'), 'campaign', ['org_id'], unique=False)
    op.create_table('campaignsettings',
    sa.Column('settings_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number_used1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number_used2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('change_number_after', sa.Integer(), nullable=True),
    sa.Column('max_calls_to_unanswered_lead', sa.Integer(), nullable=False),
    sa.Column('campaign_status', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.PrimaryKeyConstraint('settings_id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('lead',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_call_at', sa.DateTime(), nullable=True),
    sa.Column('tried_to_reach', sa.Integer(), nullable=False),
    sa.Column('sum_calls_performed', sa.Integer(), nullable=False),
    sa.Column('number_called_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('called_by', sa.Uuid(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['called_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_index(op.f('ix_lead_campaign_id'), 'lead', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_lead_org_id'), 'lead', ['org_id'], unique=False)
    op.create_index(op.f('ix_lead_phone_number'), 'lead', ['phone_number'], unique=False)
    op.add_column('call', sa.Column('campaign_id', sa.Uuid(), nullable=True))
    op.add_column('call', sa.Column('lead_id', sa.Uuid(), nullable=True))
    op.alter_column('call', 'contact_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_call_org_id'), 'call', ['org_id'], unique=False)
    op.create_foreign_key(None, 'call', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'call', 'lead', ['lead_id'], ['lead_id'])
    op.add_column('contact', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_contact_org_id'), 'contact', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_org_id'), table_name='contact')
    op.drop_column('contact', 'extra_data')
    op.drop_constraint(None, 'call', type_='foreignkey')
    op.drop_constraint(None, 'call', type_='foreignkey')
    op.drop_index(op.f('ix_call_org_id'), table_name='call')
    op.alter_column('call', 'contact_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('call', 'lead_id')
    op.drop_column('call', 'campaign_id')
    op.drop_index(op.f('ix_lead_phone_number'), table_name='lead')
    op.drop_index(op.f('ix_lead_org_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_campaign_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_table('campaignsettings')
    op.drop_index(op.f('ix_campaign_org_id'), table_name='campaign')
    op.drop_table('campaign')
    # ### end Alembic commands ###
