"""add_lead_comment_and_status_history_tables

Revision ID: 532492961e9c
Revises: fe18252261a3
Create Date: 2026-04-10 05:25:07.405617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '532492961e9c'
down_revision: Union[str, Sequence[str], None] = 'fe18252261a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leadcomment',
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.lead_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_leadcomment_lead_id'), 'leadcomment', ['lead_id'], unique=False)
    op.create_index(op.f('ix_leadcomment_org_id'), 'leadcomment', ['org_id'], unique=False)
    op.create_table('leadstatushistory',
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('new_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.lead_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_leadstatushistory_lead_id'), 'leadstatushistory', ['lead_id'], unique=False)
    op.create_index(op.f('ix_leadstatushistory_org_id'), 'leadstatushistory', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leadstatushistory_org_id'), table_name='leadstatushistory')
    op.drop_index(op.f('ix_leadstatushistory_lead_id'), table_name='leadstatushistory')
    op.drop_table('leadstatushistory')
    op.drop_index(op.f('ix_leadcomment_org_id'), table_name='leadcomment')
    op.drop_index(op.f('ix_leadcomment_lead_id'), table_name='leadcomment')
    op.drop_table('leadcomment')
    # ### end Alembic commands ###
