"""add campaigns leads campaign_settings tables

Revision ID: 68fb7f7d8f69
Revises: 7c5d97103d2e
Create Date: 2026-03-15 00:13:33.045863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68fb7f7d8f69'
down_revision: Union[str, Sequence[str], None] = '7c5d97103d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
