"""add_ring_timeout_and_agent_terminated

Revision ID: 6f903a8a1ee5
Revises: c5456f871f86
Create Date: 2026-04-17 21:07:17.802047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f903a8a1ee5'
down_revision: Union[str, Sequence[str], None] = 'c5456f871f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('agent_terminated', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_constraint(op.f('call_lead_id_fkey'), 'call', type_='foreignkey')
    op.create_foreign_key(None, 'call', 'lead', ['lead_id'], ['lead_id'])
    op.add_column('campaignsettings', sa.Column('ring_timeout_seconds', sa.Integer(), nullable=False, server_default=sa.text('15')))
    op.drop_constraint(op.f('leadcomment_lead_id_fkey'), 'leadcomment', type_='foreignkey')
    op.create_foreign_key(None, 'leadcomment', 'lead', ['lead_id'], ['lead_id'])
    op.drop_constraint(op.f('leadstatushistory_lead_id_fkey'), 'leadstatushistory', type_='foreignkey')
    op.create_foreign_key(None, 'leadstatushistory', 'lead', ['lead_id'], ['lead_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leadstatushistory', type_='foreignkey')
    op.create_foreign_key(op.f('leadstatushistory_lead_id_fkey'), 'leadstatushistory', 'lead', ['lead_id'], ['lead_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'leadcomment', type_='foreignkey')
    op.create_foreign_key(op.f('leadcomment_lead_id_fkey'), 'leadcomment', 'lead', ['lead_id'], ['lead_id'], ondelete='CASCADE')
    op.drop_column('campaignsettings', 'ring_timeout_seconds')
    op.drop_constraint(None, 'call', type_='foreignkey')
    op.create_foreign_key(op.f('call_lead_id_fkey'), 'call', 'lead', ['lead_id'], ['lead_id'], ondelete='CASCADE')
    op.drop_column('call', 'agent_terminated')
    # ### end Alembic commands ###
