/* eslint-disable */
// Generates src/environments/environment.prod.ts from .env at build time.
// Local: reads Frontend-voice/.env via dotenv.
// Vercel: process.env is populated from the project's Environment Variables — no .env file needed.

const fs = require('fs');
const path = require('path');

try {
  require('dotenv').config({ path: path.join(__dirname, '../.env') });
} catch (_) {
  // dotenv is optional on CI/Vercel where env vars come from the platform
}

const apiUrl = process.env.API_URL;

if (!apiUrl) {
  console.error('[generate-env] Missing API_URL. Set it in Frontend-voice/.env (local) or in Vercel Environment Variables (prod).');
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
export const environment = {
    production: true,
    apiUrl: '${apiUrl}',
    twilioEnabled: true,
    pollingIntervalMs: 4000,
    tokenRefreshBufferMs: 60000,
    logLevel: 'error' as const,
    campaignSecondaryFieldsEnabled: false,
    adminWhatsAppNumber: '+972509444706',
};
`;

const outPath = path.join(__dirname, '../src/environments/environment.prod.ts');
fs.writeFileSync(outPath, content);
console.log(`[generate-env] Wrote ${path.relative(process.cwd(), outPath)} (apiUrl=${apiUrl})`);
